/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/david.glb -o app/david.jsx -r public 
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/head-of-michelangelos-david-optimised-d29af50360624e5e9b1855666475380d
Title: Head Of Michelangelo's David, Optimised
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function DavidModel(props) {
  const myMesh = React.useRef()
  useFrame(({ clock }) => {
    myMesh.current.rotation.y = clock.getElapsedTime();
  })
  const { nodes, materials } = useGLTF('/models/david.glb')
  return (
    <group {...props} dispose={null}>
      <mesh ref={myMesh} geometry={nodes.Object_2.geometry} material={materials.material_0} position={[-7.061, 25, -150]} rotation={[3.129, -0.082, -0.011]} scale={0.8} />
    </group>
  )
}

useGLTF.preload('/models/david.glb')
